config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do


  resource :abouts

  resources :articles do
    resources :comments
    collection do
      post :preview
    end
  end

  resource :photos

  get 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  # post 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  get 'users/sign_up' , to: 'auth/users#new'
  delete 'users/sign_out', to: 'auth/sessions#destroy', as: 'destroy_user_session'
  scope module: 'auth' do
    resources :users do
      collection do
        get  :confirmation
        get  :new_password
        post :reset_password_mail
        get  :edit_password
        put :reset_password
      end
    end
    resource :session
    resources :roles
  end

  namespace :auth do

    get 'omniauth_callbacks/qq' , to: 'omniauth_callbacks#qq'
    get 'omniaut_authorize/redirect' , to: 'omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'


  end

  get 'notifications/index'
  delete 'notifications/clean'

  mount Sidekiq::Web => '/sidekiq',  constraints: -> (request){
    user = User.find_by_id(request.session[:user_id])
    user && user.admin?
  }

  # get 'auth/omniauth_callbacks/qq' , to: 'auth/omniauth_callbacks#qq'
  # get 'auth/omniaut_authorize/redirect' , to: 'auth/omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'



  get 'photo/*name', to: 'photos#show', format: true,constraints: { format: 'png' }
  # get 'home/about'
  root "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,except: [:index,:show]
  before_action :authenticate_admin!,except: [:index,:show,:preview]
  # GET /articles
  # GET /articles.json
  def index
    @offset = params[:offset] || 0
    @limit = params[:limit] || 10
    @total = Article.count
    @articles = Article.order("updated_at desc").offset(@offset).limit(@limit)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
     @article.hits+=1
     @article.save(touch: false)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    @body = params[:body]

    respond_to do |format|
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :text)
    end

    def authenticate_admin!
      unless current_user.publish_articles_admin?
        redirect_to root_path , notice: '您没有权限！访客不能发表博文!'
        return
      end

      if params["action"]=="new"
        return
      end
      if request.request_method == "POST"
        return
      end
      #更新和删除，需要是作者或者是管理员
      if current_user.id != @article.user_id && !current_user.admin?
        redirect_to root_path , notice: '您不是作者,没有权限！'
        return
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field article-header">
      <%= form.text_field :title, {id: :article_title , class: "form-control h1 text-center" ,placeholder: "填写标题名称"} %>
  </div>

  <%= render 'shared/editor_toolbar'%>
  <div class="field">
    <%= form.text_area :text, {id: :article_text , class: "form-control",placeholder: "仅支持Markdown格式填写内容",rows: 10} %>
  </div>



  <div class="actions">
    <%= form.submit "保存" ,{class: "btn btn-default"} %>   
    <%= link_to '取消', article.id.nil? ? articles_path : article , {class: "btn btn-default"} %> 
    
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 ">
			<%= render 'form', article: @article %>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="articles-index">
        <% @articles.each do |article| %>
          <article>
            <header>
              <h1><%= link_to article.title, article %> </h1>
            </header>
            <section>
              <p >
              <%= generate_abstract_tag(article.text,300) + (link_to " » ", article) %>
              </p>
            </section>
            <footer>
              <p class="blog-post-meta"> <%= link_to  article.user.name.blank? ? article.user.username : article.user.name , user_path(article.user_id) , {class: ""} %> | 最后更新：<%= change_time_style article.updated_at %> | <%= article.hits%>次阅读 </p>
            </footer>
          </article>
          <% if @articles.last != article %>
            <hr>
          <% end %>
        <% end %>

      </div>
      <div class="text-center">
        <ul class="pagination">
          <%= generate_pagination(total: @total,offset: @offset , limit: @limit)%>
        </ul>
      </div>
    </div> <!-- /.col-md-12 -->
  </div><!-- /.row -->
</div>
<%= render "shared/jump_toolbar"%>

app/views/articles/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<%= render 'form', article: @article %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="container">
	<div class="row">
		<div class="article col-md-10 col-md-offset-1">
			<h1 class="text-center" ><%= @article.title %></h1>
			<p class="info text-right"> <%= link_to  @article.user.name.blank? ? @article.user.email : @article.user.name , user_path(@article.user_id) , {class: ""} %> | 创建：<%= change_time_style @article.created_at%> | 最后更新：<%= change_time_style @article.updated_at %> | <%= @article.hits%>次阅读 </p>
			<p>
			  <%= raw markdown @article.text %>
			</p>


			<% if user_signed_in? && (current_user.id == @article.user_id || current_user.admin? )%>
			<%= link_to '编辑', edit_article_path(@article),{ class: "btn btn-default"} %>  <%= link_to '删除', @article, {method: :delete,class: "btn btn-default", data: { confirm: '删除后，将无法恢复！确定要删除？' }} %>
			<% end %>
			<hr>
			<h4>共收到 <%= @article.comments.length %> 条回复 </h4>
			<hr>
			<%= render @article.comments %>
			 
			<h4>评论:</h4>
			<%= form_for([@article, @article.comments.build]) do |f| %>
	
			  <p>
			    <%= f.text_area :body %>
			  </p>
			  <p>
			    <%= f.submit '提交评论' %>
			  </p>
			<% end %>
			<% unless user_signed_in? %>
			<%= render "auth/sessions/links" %>
			<% end %>
		</div>
	</div>
</div>
<%= render "shared/jump_toolbar"%>