config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do


  resource :abouts

  resources :articles do
    resources :comments
    collection do
      post :preview
    end
  end

  resource :photos

  get 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  # post 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  get 'users/sign_up' , to: 'auth/users#new'
  delete 'users/sign_out', to: 'auth/sessions#destroy', as: 'destroy_user_session'
  scope module: 'auth' do
    resources :users do
      collection do
        get  :confirmation
        get  :new_password
        post :reset_password_mail
        get  :edit_password
        put :reset_password
      end
    end
    resource :session
    resources :roles
  end

  namespace :auth do

    get 'omniauth_callbacks/qq' , to: 'omniauth_callbacks#qq'
    get 'omniaut_authorize/redirect' , to: 'omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'


  end

  get 'notifications/index'
  delete 'notifications/clean'

  mount Sidekiq::Web => '/sidekiq',  constraints: -> (request){
    user = User.find_by_id(request.session[:user_id])
    user && user.admin?
  }

  # get 'auth/omniauth_callbacks/qq' , to: 'auth/omniauth_callbacks#qq'
  # get 'auth/omniaut_authorize/redirect' , to: 'auth/omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'



  get 'photo/*name', to: 'photos#show', format: true,constraints: { format: 'png' }
  # get 'home/about'
  root "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  def actor_name
    User.find_by_id(actor_id).name
  end

  def target
    eval(target_type).find_by_id(target_id)
  end
  def second_target
    eval(second_target_type).find(second_target_id)
  end
  def read?
    !read_at.blank?
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action  :authenticate_user!
  def index
    @notifications = notifications.order("created_at desc")
  end

  def clean
    notifications.delete_all
    redirect_to notifications_index_path
  end

  private

  def notifications
    # current_user.notifications
    Notification.where(user_id: current_user.id)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_comment.html.erb
<% comment = notification.second_target %>

<% article = notification.target %>

  <div class="media-heading">
    在博文
    <%= link_to article.title, article_path(article) %> 评论了：
  </div>
  <div class="media-content">
  <% if comment.delete_flag %>
    <s><%= comment.body %></s>
  <% else %>
    <%= comment.body %>
  <% end %>
  </div>

app/views/notifications/_notification.html.erb
<%= change_time_style notification.created_at %>
<div>
  <div class="media-left">
    <%= link_to notification.actor_name, user_url(notification.actor_id), title: notification.actor_name %>
  </div>
  <div class="media-body">
    <%= render partial: "#{notification.notify_type.underscore}", locals: { notification: notification } %>  </div>
  <div class="media-right">
    <%= notification.created_at.strftime('%H:%M') %>
  </div>
</div>
<hr>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel">
        <div class="panel-body list item-list">
          <% if @notifications.blank? %>
          <p class="text-muted text-center" >暂无消息通知</p>
          <% else %>
          所有通知
          <span class="pull-right">
            <%= link_to "清空", notifications_clean_path, class: 'btn btn-sm btn-danger', id: 'btn-remove-all', method: 'delete', remote: true %>
          </span>
          <hr>

          <%= render @notifications %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>