config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do


  resource :abouts

  resources :articles do
    resources :comments
    collection do
      post :preview
    end
  end

  resource :photos

  get 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  # post 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  get 'users/sign_up' , to: 'auth/users#new'
  delete 'users/sign_out', to: 'auth/sessions#destroy', as: 'destroy_user_session'
  scope module: 'auth' do
    resources :users do
      collection do
        get  :confirmation
        get  :new_password
        post :reset_password_mail
        get  :edit_password
        put :reset_password
      end
    end
    resource :session
    resources :roles
  end

  namespace :auth do

    get 'omniauth_callbacks/qq' , to: 'omniauth_callbacks#qq'
    get 'omniaut_authorize/redirect' , to: 'omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'


  end

  get 'notifications/index'
  delete 'notifications/clean'

  mount Sidekiq::Web => '/sidekiq',  constraints: -> (request){
    user = User.find_by_id(request.session[:user_id])
    user && user.admin?
  }

  # get 'auth/omniauth_callbacks/qq' , to: 'auth/omniauth_callbacks#qq'
  # get 'auth/omniaut_authorize/redirect' , to: 'auth/omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'



  get 'photo/*name', to: 'photos#show', format: true,constraints: { format: 'png' }
  # get 'home/about'
  root "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	before_action :set_about, only: [:show, :edit, :update]
	before_action :authenticate_user!,except: [:show]
	before_action :authenticate_admin!,except: [:show]
	def show
		@users = User.where(role_id: [Role.user_role.id ,Role.admin_role.id])
	end

	def edit
	end

	def update
	    respond_to do |format|
	      if @about.update(about_params)
	        format.html { redirect_to abouts_path, notice: 'About was successfully updated.' }
	      else
	        format.html { render :edit }
	      end
	    end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
    	@about = About.first.nil? ? About.create(text: "") : About.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:text)
    end
    def authenticate_admin!
      redirect_to new_user_session_path , notice: '您没有权限，请登录管理员账号！' unless current_user.admin?
    end
end

app/views/abouts/_form.html.erb
<%= form_for(about, url: abouts_path) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <%= render 'shared/editor_toolbar'%>
  <div class="field">
    <%= form.text_area :text, {id: :about_text , class: "form-control",placeholder: "仅支持Markdown格式填写内容",rows: 10} %>
  </div>



  <div class="actions">
    <%= form.submit "保存" ,{class: "btn btn-default"} %>   
    <%= link_to '取消',  abouts_path , {class: "btn btn-default"} %> 
    
  </div>
<% end %>

app/views/abouts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 ">
			<%= render 'form', about: @about %>
		</div>
	</div>
</div>

app/views/abouts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>关于小屋</h2>
      <p class="lead"><%= raw markdown @about.text %></p>

      <% if user_signed_in? &&  current_user.admin?  %>
      <%= link_to '编辑', edit_abouts_path(@about),{ class: "btn btn-default"} %>  
      <% end %>

      <h2>当前住户</h2>
      <div class="panel-body" >
        <% @users.each do |user| %>
          <div class="user-label">
              <h4>
                <span><%= link_to  user.username ,user_path(user) ,{class: "label"}%></span>
              </h4>
          </div>
        <% end %>
      </div> 
    </div>


  </div><!-- /.row -->
</div>