config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do


  resource :abouts

  resources :articles do
    resources :comments
    collection do
      post :preview
    end
  end

  resource :photos

  get 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  # post 'users/sign_in' , to: 'auth/sessions#new' , as: 'new_user_session'
  get 'users/sign_up' , to: 'auth/users#new'
  delete 'users/sign_out', to: 'auth/sessions#destroy', as: 'destroy_user_session'
  scope module: 'auth' do
    resources :users do
      collection do
        get  :confirmation
        get  :new_password
        post :reset_password_mail
        get  :edit_password
        put :reset_password
      end
    end
    resource :session
    resources :roles
  end

  namespace :auth do

    get 'omniauth_callbacks/qq' , to: 'omniauth_callbacks#qq'
    get 'omniaut_authorize/redirect' , to: 'omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'


  end

  get 'notifications/index'
  delete 'notifications/clean'

  mount Sidekiq::Web => '/sidekiq',  constraints: -> (request){
    user = User.find_by_id(request.session[:user_id])
    user && user.admin?
  }

  # get 'auth/omniauth_callbacks/qq' , to: 'auth/omniauth_callbacks#qq'
  # get 'auth/omniaut_authorize/redirect' , to: 'auth/omniauth_callbacks#authoriz' ,as: 'omniauth_authorize'



  get 'photo/*name', to: 'photos#show', format: true,constraints: { format: 'png' }
  # get 'home/about'
  root "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= generate_html_titile(controller_name: controller_name)%>

    <%= csrf_meta_tags %>
    <%= favicon_link_tag image_path("favicon.ico") %>
    <!-- 最新版本的 jquery 文件 -->
    <!-- <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <!-- <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />
    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <!-- <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha256-ZT4HPpdCOt2lvDkXokHuhJfdOKSPFLzeAJik5U/Q+l4=" crossorigin="anonymous" />
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <!-- <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script>

    <!-- <script src="https://cdn.bootcss.com/underscore.js/1.7.0/underscore-min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js" integrity="sha256-e2+9ivHFOECPL+fu9fbFK4XbEquRtjJ3KH5enqg6STE=" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.bootcss.com/backbone.js/1.1.2/backbone-min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js" integrity="sha256-ddKDRLG4O1+xU/xZOb3BC0BKdU2T9498HIqLgd43aCU=" crossorigin="anonymous"></script>
    <!-- 最新版本的 jquery 文件 -->
    <!-- <script src="/plugins/jquery/jquery.min.js"></script> -->

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <!-- <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css" > -->

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <!-- <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap-theme.min.css" > -->

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <!-- <script src="/plugins/bootstrap/js/bootstrap.min.js" ></script> -->

    <%= stylesheet_link_tag    'app', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'app', 'data-turbolinks-track': 'reload' %>

  </head>

  <body  data-controller-name="<%= controller_name %>" >
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">九神小屋</a>       -->
        <%= link_to "九神小屋" , root_path , {class: "navbar-brand" , title: "首页"} %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li id="nav_home" ><%= link_to "首页" , root_path , {class: ""} %></li>
          <li id="nav_articles" ><%= link_to "目录" , articles_path , {class: ""} %></li>
      <li id="nav_about" ><%= link_to "关于" , abouts_path , {class: ""} %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to raw('<span class="glyphicon glyphicon-bell" aria-hidden="true"></span>'),notifications_index_path , {class: "dropdown-toggle",role: "button",'aria-haspopup':"true" ,'aria-expanded':"false"} %></li>
            <% if current_user.publish_articles_admin? %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to '发表新文章', new_article_path %></li>
                  </ul>
              </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name.blank? ? current_user.username : current_user.name%> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to current_user.username %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to '个人资料设置',user_path(current_user.id) %></li>
                <% if  current_user.admin? %>
                <li><%= link_to '角色管理',roles_path() %></li>
                <li><%= link_to '用户列表',users_path() %></li>
                <% end %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "退出" , destroy_user_session_path , {method: "delete"}%></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "登录" , new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->




    </div><!-- /.container-fluid -->
  </nav>
   <!-- <p class="notice"><%= notice %></p> -->
   <!-- <p class="alert"><%= alert %></p> -->
  <% if notice %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Well done!</strong> <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Oh snap!</strong> <%= alert %>
    </div>
  <% end %>
    <%= yield %>
    <hr>
    <div class="container">
      <div class="row">
        <footer class="col-sm-12 footer">
            <p class="text-muted text-center" >版权所有 © 2017-2020 <%= link_to "九神小屋" , root_path ,{class: "link"}%>，保留一切权利。</p>
            <p class="text-muted text-center" ><%= link_to "粤ICP备17148860号" , 'https://beian.miit.gov.cn/' ,{class: "link"}%></p>
        </footer>
      </div>
    </div>
  </body>
</html>